trigger:
  - main  # Trigger on the main branch

pool:
  vmImage: 'ubuntu-latest'

#variables:
#  AZURE_WEBAPP_NAME: '<your-web-app-name>'  # Replace with your Azure Web App name
#  AZURE_RESOURCE_GROUP: '<your-resource-group>'  # Replace with your Azure Resource Group
#  AZURE_SERVICE_CONNECTION: '<your-service-connection-name>'  # Replace with your service connection name

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Specifies JDK 11
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sqMavenPluginVersionChoice: 'latest'
    findBugsRunAnalysis: true

#- task: PublishBuildArtifacts@1
#  inputs:
#    pathToPublish: '$(Build.ArtifactStagingDirectory)'
#    artifactName: 'drop'
#
#- task: AzureWebApp@1
#  inputs:
#    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
#    appName: '$(AZURE_WEBAPP_NAME)'
#    package: '$(Build.ArtifactStagingDirectory)/*.jar'
#    runtimeStack: 'JAVA|11-java11'  # Update if using a different Java version